# COPYRIGHT_BEGIN
#  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
#  
#  Copyright (c) 2008, Cable Television Laboratories, Inc. 
#  <oc-mail@cablelabs.com>
#  
#  This program is free software; you can redistribute it and/or modify 
#  it under the terms of only version 2 of the GNU General Public License
#  as published by the Free Software Foundation.
#  
#  This file is distributed in the hope that it will be useful, but 
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   See the GNU
#  General Public License for more details.  (a copy is included 
#  that accompanied this file and can also be found at 
#  http://java.net/projects/ocap-ri/ or write to: the Free Software 
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, 
#  MA 02110-1301 USA).
#  
#  Please contact CableLabs if you need additional information or 
#  have any questions.
#  
#       CableLabs
#  
#       858 Coal Creek Cir
#  
#       Louisville, CO 80027-9750
#  
#       303 661-9100
#  
#       oc-mail@cablelabs.com
# COPYRIGHT_END
#############################################################################
#
# Build CableLabs RI MPE OS library (Win32)
#
# @author gdr - Vidiom Systems Inc
#
#############################################################################

SOURCES += \
			mpeos_file_hd.c \
			mpeos_file_romfs_image.c

include ../RI_Common/ri_common.mk

